"""Encabezados de las hojas del sistema, tomados de Setup.gs."""

from core.sheets import sheet_names

"""BKD.004.002 - Esquema de hojas
Define los encabezados que crea el comando init_sheets, equivalente a
inicializarSistema() del Apps Script.
"""

SHEET_HEADERS: dict[str, tuple[str, ...]] = {
    sheet_names.SHEET_PROJECTS: (
        "ID_Proyecto",
        "Nombre",
        "Cliente",
        "Producto",
        "Scrum_Master",
        "Estado",
        "Prioridad",
        "Fecha_Inicio",
        "Fecha_Fin_Estimada",
        "% Avance",
        "Budget_Hrs",
        "Burn_Hrs",
        "ETC_Hrs",
        "Nivel_Riesgo",
        "Dias_Desviacion",
        "Azure_Project_ID",
        "Ultima_Actualizacion",
    ),
    sheet_names.SHEET_PROJECTS_HISTORY: (
        "Timestamp",
        "ID_Proyecto",
        "% Avance",
        "Budget_Hrs",
        "Burn_Hrs",
        "ETC_Hrs",
        "Nivel_Riesgo",
        "Estado",
        "Origen_Cambio",
    ),
    sheet_names.SHEET_SPRINTS: (
        "ID_Sprint",
        "ID_Proyecto",
        "Numero_Sprint",
        "Fecha_Inicio",
        "Fecha_Fin",
        "Story_Points_Comprometidos",
        "Story_Points_Completados",
        "Story_Points_Restantes",
        "Velocity",
        "Dias_Restantes",
        "Estado",
    ),
    sheet_names.SHEET_SPRINTS_HISTORY: (
        "Timestamp",
        "ID_Sprint",
        "SP_Completados",
        "SP_Restantes",
        "Velocity",
        "Estado",
    ),
    sheet_names.SHEET_RESOURCES: (
        "ID_Recurso",
        "Nombre",
        "Rol",
        "Proyectos_Asignados",
        "Horas_Asignadas_Semana",
        "Horas_Disponibles_Semana",
        "% Carga",
        "Velocity_Individual",
    ),
    sheet_names.SHEET_RESOURCE_LOAD_HISTORY: (
        "Timestamp",
        "ID_Recurso",
        "Semana",
        "Horas_Asignadas",
        "Horas_Disponibles",
        "% Carga",
    ),
    sheet_names.SHEET_RISKS: (
        "ID_Riesgo",
        "ID_Proyecto",
        "Descripcion",
        "Impacto",
        "Probabilidad",
        "Estado",
        "Responsable",
        "Fecha_Deteccion",
        "Fecha_Revision",
        "Plan_Mitigacion",
        "Origen",
    ),
    sheet_names.SHEET_RISKS_HISTORY: (
        "Timestamp",
        "ID_Riesgo",
        "Estado",
        "Impacto",
        "Probabilidad",
        "Accion",
    ),
    sheet_names.SHEET_MINUTES: (
        "ID_Minuta",
        "ID_Proyecto",
        "ID_Sprint",
        "Fecha_Reunion",
        "Fuente",
        "Doc_URL",
        "Asistentes",
        "Resumen_IA",
        "Riesgos_Detectados",
        "Pendientes",
        "Acuerdos",
        "WorkItems_Mencionados",
        "Sentimiento_Reunion",
        "Procesado",
    ),
    sheet_names.SHEET_MINUTES_PENDING: (
        "ID_Pendiente",
        "ID_Minuta",
        "ID_Proyecto",
        "Descripcion",
        "Responsable",
        "Fecha_Compromiso",
        "Prioridad",
        "Estado",
    ),
    sheet_names.SHEET_AZURE_WORK_ITEMS: (
        "ID_WorkItem",
        "ID_Proyecto",
        "ID_Sprint",
        "Titulo",
        "Tipo",
        "Estado_Azure",
        "Responsable",
        "Prioridad",
        "Story_Points",
        "Comparacion_Daily",
        "Ultima_Sync",
    ),
    sheet_names.SHEET_AZURE_SYNC_HISTORY: (
        "Timestamp",
        "ID_Proyecto",
        "Total_WorkItems",
        "Coinciden",
        "Diferencias",
        "Sin_Actualizar",
    ),
    sheet_names.SHEET_DASHBOARD_KPIS: (
        "Timestamp",
        "Proyectos_Activos",
        "Riesgos_Altos",
        "Budget_Total",
        "Burn_Total",
        "ETC_Total",
        "Velocity_Promedio",
    ),
    sheet_names.SHEET_CONFIGURATION: (
        "Parametro",
        "Valor",
    ),
    sheet_names.SHEET_AUTOMATION_LOG: (
        "Timestamp",
        "Proceso",
        "Resultado",
        "Detalle",
        "Duracion_ms",
    ),
    sheet_names.SHEET_TIME_ENTRIES: (
        "ID_Registro",
        "Proyecto",
        "Cliente",
        "Descripcion",
        "Tarea",
        "Recurso",
        "Email",
        "Fecha",
        "Hora_Inicio",
        "Hora_Fin",
        "Duracion_Hrs",
        "Banda",
        "Costing_Rate",
        "Billable",
    ),
}
